OpenGamma/OG-Platform

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldCurveUtils.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldCurveUtilsTest.java
The methods on ``YieldCurveUtils`` that apply shifts to yield curves also add a hard-coded suffix to the curve name. This PR adds overloaded versions that allow the suffix to be specified, allowing the shifted curve to have the same name as the base curve.
=> PLT-587 - Overloads of YieldCurveUtils methods specifying curve name suffix

projects/OG-Master/src/main/java/com/opengamma/master/config/ConfigSearchRequest.java, projects/OG-Master/src/test/java/com/opengamma/master/config/ConfigSearchRequestTest.java
This PR cherry picks some commits to 2.8.x that have already been reviewed and merged to 2.9.x.
=> Topic/plt 597 - More efficient handling of wildcards in ConfigSearchRequest

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDifferenceOperator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesPercentageChangeOperator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDataSet.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDifferenceOperatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesPercentageChangeOperatorTest.java
Relative change operator now take a lag, to have changes over a multiple periods. 
Added related tests. 
Cleaned and extended tests on absolute change operator.
=> [PLAT-6889] Extended relative change operator on time series.

docs/og-analytics/worked-out-examples/worked-out-example-stir-futures-option-normal-moneyness.rst
* rst on STIRFuturesOptionNormalExpSimpleMoneynessMethodE2ETest (and STIRFuturesOptionNormalExpSimpleMoneynessGBPE2ETest).
=> [PLAT-6893] Added rst for STIR futures option with normal model

docs/og-analytics/worked-out-examples/worked-out-example-dsf-discounting.rst, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/SwapFuturesPriceDeliverableTransactionDiscountingMethodE2ETest.java
* End-to-end test for DSF including EUR, GBP and USD examples.
=>  E2E test for DSF

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/equity/option/EquityIndexFutureOption.java, projects/OG-Bloomberg/src/main/java/com/opengamma/bbg/util/BloombergEQVanillaOptionChain.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/curve/CurveNodeIdMapper.java
Minor formatting changes to match check-style required style in Eclipse.
=> [PLAT-6899] Minor formatting changes to match check-style.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldAndDiscountCurve.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldSimpleCurve.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldSimpleCurveTest.java
Create a new type of curve. The data is stored as simple rate, i.e. the discount factor for maturity "t" is computed as 1/(1+r(t)*t) where "r(t)" is the simple rate in "t" provided by the internal curve representation.
=> [PLAT-6900] Added YieldAndDiscountCurve described by simple rate.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/SquareLinearInterpolator1D.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/TimeSquareInterpolator1D.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessGBPE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/math/interpolation/SquareLinearInterpolator1DTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/math/interpolation/TimeSquareInterpolator1DTest.java
Improve SquareLinear and TimeSquare interpolator to support 0 values. Added an example of STIR futures with 0 volatility in E2E test.
TimeSquareInterpolator1D: coverage is 100%
SquareLinearInterpolator1D: coverage is 96.4%
=> [PLAT-6905]  Interpolator with 0 values. Option test with 0 volatility.

projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/conversion/FixedIncomeConverterDataProvider.java
Test coverage will be added to downstream project that encoutered this error
=> PLAT-6902 DSF analytic conversion requires close price on trade date

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/InterestRateFutureOptionMarginSecurityNormalSmileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/InterestRateFutureOptionMarginTransactionNormalSmileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/discounting/PV01CurveParametersCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessGBPE2ETest.java
* Added new methods and demonstrated the relation to the existing calculator.
=> STIR futures option methods with underlying futures price.

docs/og-analytics/worked-out-examples/worked-out-example-stir-futures-option-normal-moneyness.rst, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessGBPE2ETest.java
* Added examples of STIR futures option with negative strike rates, negative futures rate.
=> STIR futures options with negative rates

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/CouponAccrualDatesVisitor.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/CouponFixingDatesVisitor.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/CouponFixingYearFractionVisitor.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/CouponPaymentYearFractionVisitor.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/CouponTenorVisitor.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/swap/provider/CouponForwardRateVisitor.java
Tests to follow at the function level
=> PLAT-6911 FRA: Add support to cashflow visitors

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaSingleCurveCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCalculatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaSingleCurveCalculatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/description/MulticurveProviderDiscountDataSets.java
Added relevant tests and performance measurement.
=> [REQS-1035] Added computation of the sum-of-columns gamma. 

projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/description/IssuerProviderDiscountDataSets.java
Corrected name in curve GER_EUR_CURVE.
=> [PLT-864] Corrected name.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaMultiCurveCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaSingleCurveCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/MulticurveProviderDiscount.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/util/export/ExportUtils.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCalculatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaMultiCurveCalculatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/calculator/discounting/CrossGammaSingleCurveCalculatorTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/tutorial/analysis/swap/SwapGammaMultiCurveProfitJPYAnalysis.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/tutorial/analysis/swap/SwapGammaSingleCurveProfitAnalysis.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/tutorial/datasets/AnalysisMarketDataJPYSets.java
Old bug but could have an impact on some gamma computation. 
Required for some SIMM analysis (forward looking estimates(.
=> [PLT-711] Changed currency and index for a name to a List instead of a single value.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/DeltaBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/FuturesPriceBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/GammaBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/ThetaBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/VegaBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/blackbondfutures/PresentValueBlackBondFuturesOptionCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/future/BondFuturesDataSets.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionPremiumBlackExpStrikeE2ETest.java, projects/OG-Financial/src/main/java/com/opengamma/financial/convention/InMemoryConventionBundleMaster.java
Added more end-to-end tests.
Completed the relevant calculators.
Corrected some typos in the instrument dates.
=> [PLT-891] End-to-end extended tests.

projects/OG-Analytics/src/main/java/com/opengamma/financial/convention/daycount/DayCount.properties, projects/OG-Analytics/src/main/java/com/opengamma/financial/convention/daycount/DayCountFactory.java, projects/OG-Analytics/src/main/java/com/opengamma/financial/convention/daycount/DayCounts.java, projects/OG-Analytics/src/main/java/com/opengamma/financial/convention/daycount/ThirtyThreeSixtyISDA.java, projects/OG-Analytics/src/test/java/com/opengamma/financial/convention/daycount/ThirtyThreeSixtyISDATest.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/model/curve/interestrate/ImpliedDepositCurveFunction.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/model/curve/interestrate/ImpliedDepositCurveSeriesFunction.java
Add 30/360 ISDA
Add 1/1 and Act/365L to DayCounts
Remove deprecated methods
=> Enhance day counts

projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/conversion/FixedIncomeConverterDataProvider.java
=> MGN-701 inflation ts data provider fix

pom.xml, projects/OG-Web/src/main/java/com/opengamma/web/analytics/push/package-info.java, sesame/sesame-component/pom.xml, sesame/sesame-engine/pom.xml, sesame/sesame-function/pom.xml, sesame/sesame-war-main/pom.xml, sesame/sesame-web/pom.xml
Use mvn package -DskipTests -Djavadoc-jar
=> Add generation of javadoc jar

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/option/pricing/analytic/formula/NormalPriceFunction.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/volatility/NormalFromBlackImpliedVolatilityFormula.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/volatility/NormalImpliedVolatilityFormula.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/model/volatility/NormalFromBlackImpliedVolatilityFormulaTest.java
Create a method to convert Black implied volatility to Normal implied volatility using the Hagan explicit approximate formula. Reference: Hagan, P. S. Volatility conversion calculator. Technical report, Bloomberg.
=> [PLT-914] Created a normal from Black implied volatility function.

sesame/sesame-function/src/main/java/com/opengamma/sesame/equityindexoptions/DefaultEquityIndexOptionFn.java, sesame/sesame-function/src/test/java/com/opengamma/sesame/equityindexoptions/EquityIndexOptionFnTest.java
The analytics do not take the equity index option position quantity into account, so scaling has to take place in the function. This was previously missing.
=> Scaling fix for Equity Index Option PV and PV01

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/equity/Equity.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/InterestRateFutureOptionMarginSecurityBlackSsviPriceMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/volatility/smile/function/SSVIVolatilityFunction.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackBondFuturesSsviConstantPriceProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackBondFuturesSsviExpiryPriceProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackBondFuturesSsviPriceProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackStirFuturesSsviPriceConstantProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackStirFuturesSsviPriceExpiryProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/BlackStirFuturesSsviPriceProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/function/PiecewisePolynomialFunction2D.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/HermiteCoefficientsProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/data/Interpolator2DDataBundle.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFutureOptionMarginSecurityBlackSsviPriceMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/InterestRateFutureOptionMarginSecurityBlackSsviPriceMethodTest.java
Extend SSVI implementation to expiry dependent rho and eta.
=> Added provider for SSVI volatility formula for Bond and Stir futures.
