projects/OG-Master/src/main/java/com/opengamma/master/config/ConfigSearchRequest.java, projects/OG-Master/src/test/java/com/opengamma/master/config/ConfigSearchRequestTest.java
This PR changes the way wildcards are handled in ``ConfigSearchRequest`` to address performance issues when using ``InMemoryConfigMaster``.
Regex patterns are only created if the name contains wildcard characters. Also the patterns are created when the name is set rather than every time the ``match()`` method is called.
=> PLT-597 - More efficient handling of wildcards in ConfigSearchRequest

projects/OG-Financial/src/test/java/com/opengamma/financial/analytics/ircurve/FutureMonthCodeCurveInstrumentProviderTest.java
Test on FutureMonthCodeCurveInstrumentProvider is clock dependent. This fix make sure that the test will pass in the future.
The actual main functionality is not test anymore. An improved test should be added.
=> [PLAT-6891] Change tests to pass in 2015 and after.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/NormalSTIRFuturesExpSimpleMoneynessProvider.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/NormalSTIRFuturesExpSimpleMoneynessProviderDiscount.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/description/interestrate/NormalSTIRFuturesProviderInterface.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/InterestRateFutureOptionMarginNormalSmileMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessGBPE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessMethodE2ETest.java
The smile description for STIR futures in the Bachelier/normal model is stored in the "NormalSTIRFuturesExpSimpleMoneynessProvider". This PR add a flag that allows to select a moneyness on the price or on the rate (1-price).
The flag is the variable _moneynessOnPrice;
Its impact is on line 69, where there is now a switch for the moneyness definition: 
double simpleMoneyness = _moneynessOnPrice ? strikePrice - futuresPrice : futuresPrice - strikePrice;
=> [REQS-845] Add flexibility to choose between price and rate simple moneyness.

docs/og-analytics/calculators/PresentValueDiscountingCalculator.rst, docs/og-analytics/worked-out-examples/worked-out-example-stir-futures-discounting.rst, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/datasets/StandardDataSetsMulticurveEUR.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionMarginTransactionBlackExpLogMoneynessMethodE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesOptionNormalExpSimpleMoneynessMethodE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/STIRFuturesTransactionDiscountingMethodE2ETest.java
Added a detailed description of the STIR futures end-to-end example. The example covers price, pv, par rate and bucketed PV01.
=> [PLAT-6892] Added documentation on STIR futures E2E test. 

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDifferenceOperator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDataSet.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesDifferenceOperatorTest.java
The TimeSeriesDifferenceOperator previously computed one period absolute return or difference for a time series. This PR extend the operator to be able to compute return on a flexible period. Returns on 2 or 5 day periods are often used in HVaR by CCPs.
=> [PLAT-6888] Extended the TS difference operator to accept flexible lag.

projects/OG-Analytics/src/main/java/com/opengamma/financial/convention/daycount/ActualNL.java, projects/OG-Analytics/src/test/java/com/opengamma/financial/convention/daycount/ActualNLTest.java
Failed to handle start in standard year and end in leap year.
Logic for NL/365 is (actual days between two dates minus any leap days) / 365. Replacement implementation is taken from OG-Commons.
=> PLAT-6778 - Fix ActualNL day count

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesWeightedVolatilityOperator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/timeseries/util/TimeSeriesWeightedVolatilityOperatorTest.java
Added flexibility to the Exponentially Weighted Moving Average time series operator.
There is now the possibility to have a seed period for the moving average (the volatility is computed as a standard unweighted volatility in the seed period). 
The operator used for the return itself is flexible also, in particular it is possible to use a return with a lag.
=> [PLAT-6890] Add flexibility in the EWMA time series operator.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/FuturesPriceBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/FuturesPriceBlackSensitivityBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/calculator/FuturesPriceCurveSensitivityBlackBondFuturesCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFutureOptionMarginSecurityBlackSmileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionMarginSecurityBlackBondFuturesMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/future/provider/FuturesSecurityBlackBondFuturesMethod.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionMarginSecurityBlackExpLogMoneynessMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionMarginSecurityBlackFlatMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionMarginTransactionBlackExpLogMoneynessMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/future/provider/BondFuturesOptionMarginTransactionBlackFlatMethodTest.java
Change the Bond Futures Option calculator to optionaly take a pricer for the underlying BondFutures.
This will give the flexibility to the user to change the bond futures behavior and getting the bond futures options directly without recoding all the methods.
=> [PlAT-6903] Change the Bond Futures Option underlying pricer.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondSecurityDiscountingMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldPeriodicAddZeroFixedCurve.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/interestrate/curve/YieldPeriodicCurve.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/curve/YieldPeriodicAddZeroFixedCurveTest.java
Corrected “YieldPeriodicAddZeroFixedCurve”. Now child of YieldAndDiscountCurve. Methods getInterestRate and getInterestRateParameterSensitivity corrected.
=> [PLAT-6901] Corrected YieldPeriodicAddZeroFixedCurve.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/volatility/surface/VolatilitySurface.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/model/volatility/surface/VolatilitySurfaceTest.java
This PR adds tenor information to ``VolatilitySurface``. Previously the expiry values could only be referred to by specifying the exact year fraction which doesn't provide a usable way to define scenario shocks. Storing the expiry tenor for each point in the surface allows scenario shocks to be specified using tenors which is what users would expect.
=> PLT-641 -Add tenor information to VolatilitySurface

projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/datasets/StandardDataSetsMulticurveUSDGBP.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCrossCurrencyUsdEurE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCrossCurrencyUsdGbpE2ETest.java
Added end-to-end examples of cross-currency swaps
- with exchange of notional 
- with and without FX reset. 
Used for comparison with V3.0.
=> [PLT-630] Added examples of XCcy swaps

projects/OG-Financial/src/main/java/com/opengamma/financial/convention/HolidaySourceCalendarAdapter.java
Holiday look up would be done based on the region currency instead of the actual region code for a specific use case that no longer exists. So we can revert back to the generic behavior.
=> [PLT-870] Removing holiday look up based on currency

projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/DiscreteQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/ExcelInterpolationQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/IndexAboveQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/InterpolationQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/MidwayInterpolationQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/NearestIndexQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/QuantileCalculationMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/SampleInterpolationQuantileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/statistics/descriptive/SamplePlusOneInterpolationQuantileMethod.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/math/statistics/descriptive/QuantileCalculationMethodTest.java
From a discrete sample of a distribution, there several ways to estimate a quantile. Different scenario based VaR methods may use different estimator. In particular, CCPs in their IM methodologies are using different approaches.
This PR created a quantile calculation method hierarchy. 
4 estimator versions have been implemented:
- discrete: nearest and index above
- interpolation: midway and sample points
The methods take as an input the sample as an array. If relevant, the input object could be changed to a time series or a list.
This PR should be ported to Analytics 3.0 after reviewed and merged.
=> [PLT-865] Quantile calculation methods.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilder.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilderTest.java
FloatingAnnuityDefinitionBuilder was using the wrong day count when computing the accrual factor for the fixing period. The builder was using the day-count of the leg instead of the day-count of the index.
Added a test checking that particular number.
=> [PLT-903] Corrected day count of fixing accrued. Added a test.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/forex/definition/ForexOptionDigitalDefinition.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/forex/provider/ForexOptionDigitalCallSpreadBlackSmileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/forex/provider/ForexOptionVanillaBlackSmileMethod.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/model/volatility/surface/SmileDeltaTermStructureParameters.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/blackforex/PresentValueCurveSensitivityForexStaticReplicationSmileCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/blackforex/PresentValueForexStaticReplicationSmileCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/forex/provider/ForexOptionDigitalE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/forex/provider/ForexOptionVanillaBlackSmileMethodTest.java
* Created calculators calling ForexOptionDigitalCallSpreadBlackSmileMethod to compute bucketed curve sensitivity. 
* Added delta method parallel to gamma in the call spread method class. 
* Added absolute delta calculation in reverse order. 
* Minor bug fixed. 
* Created E2E test for digital options, which is mainly print test and turned off by default.
=> e2e test for fx digital options

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/inflation/ParRateInflationDiscountingCalculator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/provider/calculator/inflation/ParSpreadInflationMarketQuoteCurveSensitivityDiscountingCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/inflation/provider/CouponInflationZeroCouponMonthlyDiscountingMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/inflation/provider/SwapZeroCouponInflationDiscountingUsdE2ETest.java
Added par rate calculator for zero-coupon swaps with compounded fixed leg. This is the type of fixed leg used in inflation zero-coupon swaps.
Added an example in inflation swap E2E example.
=> Par Rate calculator for inflation.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/swap/provider/CouponForwardRateVisitor.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/CouponForwardRateVisitorTest.java
The calculator CouponForwardRateVisitor returns the forward rate for different coupons types. The type CouponIborAverage was not covered by the calculator while it should be.
=> [PLT-907] In CouponForwardRateVisitor, added CouponIborAverage.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilder.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/payment/CouponIborSpreadDefinition.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/schedule/ScheduleCalculator.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilderTest.java
The fixing date should be computed from the start accrual dates and then the "reset" dates used for the forward rate computation should be computed from there. Currently the start reset period date is the start accrual date. This can cause error when there is a non standard fixing offset or potentially when the fixing and payment calendars are not the same.
=> PLT-906: Incorrect computation of fixing and reset dates in FloatingAnnuityDefinitionBuilder

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilder.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilderTest.java
The builder "FloatingAnnuityDefinitionBuilder" created for swaps building for margining does not compute the weights for stub interpolation correctly. The interpolation should be done on the number of days. The current code uses ACT/ACT ISDA daycount. This both slow and incorrect in leap years.
Added relevant test.
=> [PLT-908] Corrected stub interpolation weights.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/annuity/FixedAnnuityDefinitionBuilder.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/annuity/FixedAnnuityDefinitionBuilderTest.java
FixedAnnuityDefinitionBuilder: builder created for margining project to build swaps.
When the annuity is a zero-coupon (frequency = Period.ZERO), the payment date is adjusted but not the end-accrual date and the accrual factor.
=> [PLT-909] Corrected end date adjustment for zero-coupon case in Fixed annuity builder.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilder.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/instrument/annuity/FloatingAnnuityDefinitionBuilderTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCalculatorE2ETest.java
FixedAnnuityDefinitionBuilder: builder created for margining project to build swaps.
When created a Ibor coupon which is using a unique index different from the main index of the leg, the reset dates are computed using the main index, not the coupon index.
=> FloatingAnnuityDefinitionBuilder: incorrect reset date with stub

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/instrument/fra/ForwardRateAgreementDefinition.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/fra/derivative/ForwardRateAgreement.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/model/fixedincome/FraCashFlowDetailsCalculator.java, sesame/sesame-function/src/main/java/com/opengamma/sesame/fra/DiscountingFRACalculator.java, sesame/sesame-function/src/main/java/com/opengamma/sesame/fra/DiscountingFRAFn.java, sesame/sesame-function/src/main/java/com/opengamma/sesame/fra/FRACalculator.java, sesame/sesame-function/src/main/java/com/opengamma/sesame/fra/FRAFn.java, sesame/sesame-function/src/test/java/com/opengamma/sesame/fra/FraPricingTest.java
Adds ability to request cashflows on a fra trade or security.
Approach is to reuse the cashflow domain model for IRS for reporting consistency. Whilst in reality only a single net cashflow exists for a FRA, here we separate out the fixed rate vs index rate exposures so that the PV of each can be seen separately. This results in two distinct cashflows: one based on the fixed rate and another on the forward rate of the index.
Output measures: `RECEIVE_LEG_CASH_FLOWS` and `PAY_LEG_CASH_FLOWS`, currently only used for IRS, are reused here. In this context the "receive" cashflow is the one with a positive PV; the "pay" one negative. The net cashflow PVs equal the overall PV of the FRA, as enforced by the test.
This PR also adds two missing `toString()` methods to the analytics FRA classes.
=> [MGN-845] Cashflows for fras

RELEASE-NOTES.md, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/function/PiecewisePolynomialFunction1D.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/ConstrainedCubicSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/CubicSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/LinearInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/MonotoneConvexSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/MonotonicityPreservingCubicSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/MonotonicityPreservingQuinticSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/NaturalSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/NonnegativityPreservingCubicSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/NonnegativityPreservingQuinticSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/PiecewiseCubicHermiteSplineInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/PiecewisePolynomialInterpolator.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/interpolation/PiecewisePolynomialResult.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/matrix/DoubleMatrix1D.java, projects/OG-Analytics/src/main/java/com/opengamma/analytics/math/matrix/DoubleMatrix2D.java
Many interpolators were previously using copying forms of
DoubleMatrix2D initialization, DoubleMatrix2D.getRowVector(),
and DoubleMatrix1D initialization. This change gives copy-free
forms of those methods (but preserves copy-by-default normal
semantics) and through evaluation of all interpolators using
the methods determines whether it's safe to use the copy-free
forms and uses them where appropriate.
=> [PLT-912] Avoid unnecessary copies in interpolation.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedSecurityDiscountingMethod.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedDiscountingE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedSecurityDiscountingMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/swap/provider/SwapCalculatorTest.java
When the first coupon to be paid was already fixed, the code was attempting an illegal cast to obtain the coupon rate. Behavior changed for "US_IL_REAL" convention. This is the convention used for TIPS.
The conventions "INDEX_LINKED_FLOAT" and "UK_IL_BOND" used for UK Linked Gilts have not been changed yet.
=> Correct error in TIPS yield when the first coupon was already fixed.

projects/OG-Analytics/src/main/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedSecurityDiscountingMethod.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedDiscountingE2ETest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedSecurityDiscountingMethodGBPTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/interestrate/bond/provider/BondCapitalIndexedSecurityDiscountingMethodTest.java, projects/OG-Analytics/src/test/java/com/opengamma/analytics/financial/provider/description/MulticurveProviderDiscountDataSets.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/model/fixedincome/FixedLegCashFlows.java, projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/model/fixedincome/FloatingLegCashFlows.java
- Corrected yield computation for "US I/L REAL YLD" convention (TIPS)
- Re-enabled tests with yield/price hard-coded and externally provided.
- Cleaned historical data set for US CPI-U
=> Corrected yield formula for US inflation-linked bonds.

pom.xml
Margining is explicitly depending upon powermock 1.6.2 and mockito 1.10.19
=> Update powermock version to line up with margining

projects/OG-Financial/src/main/java/com/opengamma/financial/analytics/conversion/InterestRateSwapSecurityConverter.java
If either leg is null, or any of the 4 leg level dates are null, then the existing behavior of using values from the security is preserved.
=> [MGN-899] Update swap converter to properly use leg effective termination date if present
